from app.schemas.common import PaginatedResponse
from app.schemas.enums import UserRole, TipoObservacao, Turno, StatusRegistro, Severity, ReportType
from app.schemas.ofs import (
    OfsCreateRequest,
    OfsUpdateRequest,
    OfsCancelRequest,
    OfsEditLogEntry,
    OfsResponse,
    OfsListItem,
    OfsDetailResponse,
    OfsCancelResponse,
    # Legacy OFS aliases (backward compat)
    OfcCreateRequest,
    OfcUpdateRequest,
    OfcCancelRequest,
    OfcEditLogEntry,
    OfcResponse,
    OfcListItem,
    OfcDetailResponse,
    OfcCancelResponse,
)
from app.schemas.user import (
    UserCreateRequest,
    UserUpdateRequest,
    UserResponse,
    UserListItem,
    PasswordChangeRequest,
)
from app.schemas.metrics import (
    WeeklyMetricsResponse,
    ChartDataResponse,
    ChartDataItem,
    WeeklyEvolutionItem,
    WeeklyEvolutionResponse,
    CompanyRankingItem,
    CompanyRankingResponse,
    UserRankingItem,
    UserRankingResponse,
)
from app.schemas.target import (
    TargetCreateRequest,
    TargetResponse,
)

__all__ = [
    "PaginatedResponse",
    "UserRole",
    "TipoObservacao",
    "Turno",
    "StatusRegistro",
    "Severity",
    "ReportType",
    "OfsCreateRequest",
    "OfsUpdateRequest",
    "OfsCancelRequest",
    "OfsEditLogEntry",
    "OfsResponse",
    "OfsListItem",
    "OfsDetailResponse",
    "OfsCancelResponse",
    # Legacy OFS aliases
    "OfcCreateRequest",
    "OfcUpdateRequest",
    "OfcCancelRequest",
    "OfcEditLogEntry",
    "OfcResponse",
    "OfcListItem",
    "OfcDetailResponse",
    "OfcCancelResponse",
    "UserCreateRequest",
    "UserUpdateRequest",
    "UserResponse",
    "UserListItem",
    "PasswordChangeRequest",
    "WeeklyMetricsResponse",
    "ChartDataResponse",
    "ChartDataItem",
    "WeeklyEvolutionItem",
    "WeeklyEvolutionResponse",
    "CompanyRankingItem",
    "CompanyRankingResponse",
    "UserRankingItem",
    "UserRankingResponse",
    "TargetCreateRequest",
    "TargetResponse",
]
